INSERT INTO ADMINS(LOGIN, PASSWORD, LOGGED_IN) VALUES ('admin', 'admin', false);
INSERT INTO ADMINS(LOGIN, PASSWORD) VALUES ('sa', 'sa');

INSERT INTO USERS(NAME, PASSWORD) VALUES ('user', 'user');

INSERT INTO TASKS(USER_ID, NAME) VALUES (1, 'photo');
